import type { Metadata } from "next";
import localFont from "next/font/local";
import Provider from "./Provider";
import Header from "./components/Header";
// import "./globals.scss";
// import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // if (true) {
  //   throw new Error("This is a test error at the root layout level");
  // }
  return (
    <html lang="en">
      <Provider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
          <h1>Root Layout</h1>
          {children}
          <div className="pageContainer">Test me</div>
        </body>
      </Provider>
    </html>
  );
}
